#development version
version: '2'

services:

  redis:
    image: redis:3.2
    ports:
      - 16379:6379
    networks:
      - foo

  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    networks:
      - foo
    volumes:
      - ./:/var/www/mail-api
      - ./assets/vhost/nginx/mail-api-docker.conf:/etc/nginx/conf.d/default.conf
    links:
      - php_fpm

  php_fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/mail-api
    container_name: mailapi_php_fpm_1
    domainname: localdomain
    hostname: mailapi_php_fpm_1
    networks:
        - foo
    extra_hosts:
      - "localhost.localdomain:127.0.0.1"
    links:
      - redis
    dns:
      - 10.0.14.201
      - 10.0.14.202

networks:
  foo:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.0.0/16
         gateway: 172.10.5.254
         aux_addresses:
          php_fpm: 172.10.1.2
          webserver: 172.10.1.3
          redis: 172.10.1.4